# SPDX-FileCopyrightText: 2026 Defensive Lab Agency
# SPDX-FileContributor: u039b <git@0x39b.fr>
#
# SPDX-License-Identifier: GPL-3.0-or-later

import abc
from pathlib import Path


class AbstractCapture(abc.ABC):
    """
    Abstract base class for capture mechanisms.

    This class defines the interface for capture implementations, including
    methods to start and stop the capture process, retrieve results, and
    access the output file.

    Subclasses must implement all abstract methods.
    """

    name: str = None
    """Name identifier for the capture instance."""

    @abc.abstractmethod
    def start_capture(self):
        """
        Start the capture process.

        This method should be implemented by subclasses to initiate
        the capture mechanism.

        Raises:
            NotImplementedError: If not implemented in subclass.
        """
        pass

    @abc.abstractmethod
    def stop_capture(self):
        """
        Stop the capture process.

        This method should be implemented by subclasses to terminate
        the capture mechanism.

        Raises:
            NotImplementedError: If not implemented in subclass.
        """
        pass

    @abc.abstractmethod
    def get_result(self) -> dict:
        """
        Retrieve the result of the capture.

        Returns:
            dict: The result data from the capture.

        Raises:
            NotImplementedError: If not implemented in subclass.
        """
        pass

    @abc.abstractmethod
    def get_output_file(self) -> Path:
        """
        Get the path to the output file generated by the capture.

        Returns:
            Path: Path to the output file.

        Raises:
            NotImplementedError: If not implemented in subclass.
        """
        pass
